### ISSUE TITLE
Still doesn't work. | 1kb sized output files

### ISSUE THREAD

**Issue by Aeyth8** [rm-NoobInCoding/UnrealReZen#40] opened 2024-09-15 03:15 UTC
I know I've correctly formatted it, it even says that it was successful.

But when I open the output folder each file is empty, they're all 1kb.

```C:\Users\Aeyth\Downloads\UnrealReZen_V01\UnrealReZen.exe -g "C:\SavedVer\ArchiveLo\Game\GameName\Content\Paks" -c C:\Users\Aeyth\Downloads\UnrealReZen_V01\Input\GameName\Content -e GAME_UE4_27 -a 0xF1613F25F75AAA1B0E27E624A0F9735973597597AUOW -o C:\Users\Aeyth\Downloads\UnrealReZen_V01\Output\Output.utoc```

**Comment by rm-NoobInCoding** [comment] 2024-09-15 07:31
Probably duplicate of #38

**Comment by Aeyth8** [comment] 2024-09-15 15:17
It isn't.

**Comment by Aeyth8** [comment] 2024-09-15 15:17
It isn't.

**Comment by rm-NoobInCoding** [comment] 2024-09-15 15:54
Check your patch in the game. Not in fmodel

**Comment by Aeyth8** [comment] 2024-09-15 16:27
Already did both.

.

Just admit it doesn't work

**Comment by rm-NoobInCoding** [comment] 2024-09-15 16:52
admit what? You are making an issue without enough info (like the patch file or the ways you tried) and you expect me to solve it? My tool not working for all games and it needs to be tested more. Give me the info that I want for solving your problem or make your own tool.

**Comment by Aeyth8** [comment] 2024-09-18 22:21
Your entire instructions are absolute garbage, everything is vague and you have to figure them out on your own.
Your tool never worked and still never works, I told you what I did, I gave you the specific command, I literally did all the things I needed to do.

It outputs to 1kb every single time, your code isn't working and everyone else says the same, until I see a single person vouch for you claiming that it works, and providing proof, then I'll actually believe you.

**Comment by rm-NoobInCoding** [comment] 2024-09-18 23:06
Ah you don't know any other words then "garbage" do you? lol
Nevermind, don't use my tool until it gets fixed. Or idk ask other garbage programmer to do your job.

**Comment by rm-NoobInCoding** [comment] 2024-09-18 23:07
Issue closed until my {garbage} tool gets fixed.

**Closed by rm-NoobInCoding** 2024-09-18 23:07 UTC
